# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  label:
    types:
      - created
  push:
    branches:
      - master
      - alpha
      - beta
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn prepack

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npx semantic-release -r $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          GH_TOKEN: ${{secrets.gh_token}}
          GIT_AUTHOR_NAME: 'AutoCloud Deploy Bot'
          GIT_AUTHOR_EMAIL: 'no-reply@loudcloud.dev'
          GIT_COMMITTER_NAME: 'AutoCloud Deploy Bot'
          GIT_COMMITTER_EMAIL: 'no-reply@loudcloud.dev'


  notify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: |
          echo $GITHUB_REF_NAME
          curl -X POST --data-urlencode "payload={\"attachments\":[{\"fallback\":\"$GITLAB_USER_NAME released new $CI_PROJECT_TITLE version $GITHUB_REF_NAME\",\"color\":\"good\",\"title\":\"Version $GITHUB_REF_NAME of $CI_PROJECT_NAME released\",\"title_link\":\"$CI_PROJECT_URL\/-\/tags\/$GITHUB_REF_NAME\",\"fields\":[{\"title\":\"Tag\",\"value\":\"<$CI_PROJECT_URL\/commits\/$GITHUB_REF_NAME|$GITHUB_REF_NAME>\",\"short\":true},{\"title\":\"Commit\",\"value\":\"<$CI_PROJECT_URL\/tree\/$CI_COMMIT_SHA|$CI_COMMIT_TITLE>\",\"short\":true}],\"footer\":\"$CI_PROJECT_NAME\",\"ts\":\"$( date +%s )\"}]}" https://hooks.slack.com/services/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	